__base	equ	0
	define	1,zhangdao_sucess_msg 	
	define	1,zhangdao_over_msg 	
	define	1,daoying_sucess_msg 	
	define	1,sanhua_sucess_msg 	
	define	1,sanhua_over_msg 	
	define	1,liulang_sucess_msg 	
	define	1,luoying_sucess_msg 	
	define	1,luoying_shoot_msg 	
	define	1,luoying_dodge_msg 	
	define	1,luoying_shoot_msg1 	
	define	1,luoying_dodge_msg1 	
	define	1,feizhi_sucess_msg 	
	define	1,feizhi_shoot_msg 	
	define	1,feizhi_dodge_msg 	
	define	1,honglian_sucess_msg 	
	define	1,leidong_sucess_msg 	
	define	1,fenshen_sucess_msg 	
	define	1,fenshen_over_msg 	
	define	1,yianmu_sucess_msg 	
	define	1,yianmu_over_msg 	
	define	1,lianzhan_sucess_msg 	
	define	1,yidao_sucess_msg 	
	define	1,chan_sucess_msg 	
	define	1,chan_shoot_msg 	
	define	1,chan_dodge_msg 	
	define	1,lian_sucess_msg 	
	define	1,lian_over_msg 	
	define	1,taoyue_sucess_msg 	
	define	1,ji_sucess_msg 	
	define	1,ji_shoot_msg 	
	define	1,ji_shoot_msg1 	
	define	1,ji_dodge_msg 	
	define	1,luanhuan_sucess_msg 	
	define	1,luanhuan_shoot_msg 	
	define	1,luanhuan_dodge_msg 	
	define	1,yinyang_sucess_msg 	 
	define	1,yinyang_attack_msg 	
	define	1,yinyang_shoot_msg 	
	define	1,yinyang_dodge_msg 	
	define	1,zhen_sucess_msg 	
	define	1,zhen_dodge_msg 	
	define	1,zhen_shoot_msg 	
	define	1,zhen_shoot_msg1 	
	define	1,zhen_dodge_msg1 	
	define	1,bingxin_sucess_msg 	
	define	1,bingxin_over_msg 	
	define	1,liuchu_sucess_msg 	
	define	1,shengui_sucess_msg 	
	define	1,shengui_shoot_msg 	
	define	1,shengui_dodge_msg 	
	define	1,yianmu_fail_msg 	
	define	1,heal_enable_msg 
	define	1,heal_maxneili_msg 
	define	1,heal_nohurt_msg 
	define	1,heal_badhurt_msg 
	define	1,heal_sucess_msg 
	define	1,heal_over_msg 
	define	1,heal_level_msg 
	define	1,dazuo_level_msg 
	define	1,heal_noeff_msg 
	define	1,heal_noeff_msg1 
	define	1,recover_over_msg 
	define	1,recover_hp_msg 
	define	1,jiali_flow_msg 
	define	1,level_msg 
	define	1,suit_msg 
	define	1,neili_msg 
	define	1,not_neili_msg 
	define	1,using_msg 
	define	1,busy_msg 
	define	1,man_busy_msg 
	define	1,npc_busy_msg 
	define	1,not_str_msg 
